image: fave:latest

variables:
  DIRPATH: /home/fave-code
  PYTHONPATH: $DIRPATH/fave

stages:
  - pre
  - build
  - test
  - deploy
  - bench

build_docker:
  stage: pre
  script:
    - sudo docker build -t fave:latest .

build_np:
  stage: build
  script:
    - sudo docker run fave:latest make -j -C $DIRPATH/net_plumber/build
  dependencies:
    - build_docker

lint_fave:
  stage: build
  script:
    - sudo docker run fave:latest bash $DIRPATH/fave/test/lint_test.sh
  dependencies:
    - build_docker

test_np:
  stage: test
  script:
      sudo docker run fave:latest make -j -C $DIRPATH/net_plumber/build test
  dependencies:
    - build_docker

test_fave:
  stage: test
  script:
    - sudo docker run -e PYTHONPATH=$PYTHONPATH fave:latest python2-coverage run $DIRPATH/fave/test/unit_tests.py # && python2-coverage report
  dependencies:
    - build_docker

test_fpl:
  variables:
    PYTHONPATH: $DIRPATH/policy-translator
  stage: test
  script:
    - sudo docker run -e PYTHONPATH=$PYTHONPATH fave:latest python $DIRPATH/policy-translator/test/unit_tests.py
  dependencies:
    - build_docker

deploy_fave:
  stage: deploy
  script:
    - sudo docker run -e PYTHONPATH=$PYTHONPATH fave:latest /bin/bash -c "make -j -C $DIRPATH/net_plumber/build install && cd $DIRPATH/fave && python2 $DIRPATH/fave/test/test_rpc.py"
    - sudo docker run -e PYTHONPATH=$PYTHONPATH fave:latest /bin/bash -c "make -j -C $DIRPATH/net_plumber/build install && cd $DIRPATH/fave && bash $DIRPATH/fave/examples/example.sh"
  dependencies:
    - build_docker

bench_ifi:
  stage: bench
  script:
    - sudo docker run -e PYTHONPATH=$PYTHONPATH fave:latest /bin/bash -c "make -j -C $DIRPATH/net_plumber/build install && cd $DIRPATH/fave && python2 $DIRPATH/fave/bench/wl_ifi/benchmark.py"
  dependencies:
    - build_docker

bench_up:
  stage: bench
  script:
    - sudo docker run -e PYTHONPATH=$PYTHONPATH fave:latest /bin/bash -c "make -j -C $DIRPATH/net_plumber/build install && cd $DIRPATH/fave && python2 $DIRPATH/fave/bench/wl_up/benchmark.py"
  dependencies:
    - build_docker

bench_up_ruleset:
  stage: bench
  script:
    - sudo docker run -e PYTHONPATH=$PYTHONPATH fave:latest /bin/bash -c "make -j -C $DIRPATH/net_plumber/build install && cd $DIRPATH/fave && python2 $DIRPATH/fave/bench/wl_tum/benchmark.py"
  dependencies:
    - build_docker

bench_tum:
  stage: bench
  script:
    - sudo docker run -e PYTHONPATH=$PYTHONPATH fave:latest /bin/bash -c "make -j -C $DIRPATH/net_plumber/build install && cd $DIRPATH/fave && bash $DIRPATH/fave/scripts/generate-pgf-ruleset.sh $DIRPATH/fave/bench/wl_tum && python2 $DIRPATH/fave/bench/wl_tum/benchmark.py -4 -r $DIRPATH/fave/bench/wl_tum/rulesets/tum-ruleset"
  dependencies:
    - build_docker
