default:
  script:
    - sudo docker build -t fave:latest .
#    - docker run fave:latest

image: fave:latest

variables:
  DIRPATH: /home/fave-code
  PYTHONPATH: $DIRPATH/fave

stages:
  - build
  - test
  - deploy

build_np:
  stage: build
  script:
    - sudo docker run fave:latest make -C net_plumber/build

lint_fave:
  stage: build
  script:
    - sudo docker run fave:latest bash fave/test/lint_test.sh

test_np:
  stage: test
  script:
    - sudo docker run fave:latest net_plumber/build/net_plumber --test

test_fave:
  stage: test
  script:
    - sudo docker run fave:latest python2-coverage run fave/test/unit_tests.py
    - sudo docker run fave:latest python2-coverage report

test_fpl:
#  inherit:
#    variables: [DIRPATH]
  variables:
    PYTHONPATH: $DIRPATH/policy_translator
  stage: test
  script:
    - sudo docker run fave:latest python policy_translator/test/unit_tests.py

deploy_np:
  stage: deploy
  script:
  - sudo docker run fave:latest sudo ln -sf `pwd`/net_plumber/build/net_plumber /usr/bin/net_plumber

deploy_fave:
  stage: deploy
  script:
  - sudo docker run fave:latest python2 test/test_rpc.py
  - sudo docker run fave:latest bash examples/example.sh

bench_fave:
  stage: deploy
  script:
    - sudo docker run fave:latest echo "TODO implement fave benchmarks"
