#default:

variables:
  DIRPATH: /home/fave-code
  PYTHONPATH: $DIRPATH/fave

stages:
  - build
  - test
  - deploy
  - bench

prepare_docker:
  stage: .pre
  script:
    - docker build -t fave:latest .
    - docker run fave:latest

build_np:
  stage: build
  script:
    - docker run fave:latest cd net_plumber/build && make && cd ../..

lint_fave:
  stage: build
  script:
    - docker run fave:latest bash fave/test/lint_test.sh

test_np:
  stage: test
  script:
    - docker run fave:latest net_plumber/build/net_plumber --test

test_fave:
  stage: test
  script:
    - docker run fave:latest python2-coverage run fave/test/unit_tests.py
    - docker run fave:latest python2-coverage report

test_fpl:
  stage: test
  inherit:
    variables: [DIRPATH]
  variables:
    PYTHONPATH: $DIRPATH/policy_translator
  script:
    - docker run fave:latest python policy_translator/test/unit_tests.py

deploy_np:
  stage: deploy
  script:
  - docker run fave:latest sudo ln -sf `pwd`/net_plumber/build/net_plumber /usr/bin/net_plumber

deploy_fave:
  stage: deploy
  script:
  - docker run fave:latest python2 test/test_rpc.py
  - docker run fave:latest bash examples/example.sh

bench_fave:
  stage: bench
  script:
    - docker run fave:latest echo "TODO implement fave benchmarks"
