#!/usr/bin/env python3

# -*- coding: utf-8 -*-

# Copyright 2026 Claas Lorenz <claas_lorenz@genua.de>

# This file is part of FaVe.

# FaVe is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# FaVe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with FaVe.  If not, see <https://www.gnu.org/licenses/>.

""" What the Delta-net traces contain: the census, DERIVED (`TRACES.md`).

Same reasoning as `bench/wl_cloud/cloud_census.py`, and the same mechanism:
`TRACES.md` is GENERATED by this module and pinned byte for byte by
`test/test_deltanet_census.py`. Editing it by hand is a test failure.

The reason it exists here is sharper than "consistency", because these figures
had ALREADY rotted. `deltanet-traces/README.md` and CLOUD_BENCH_PLAN.md §2 both
carried three measurements taken by hand at vendoring time, and all three were
wrong:

  1. "the fourth field takes 18 distinct values in **180-220**" -- the count is
     right and the range is not. It is 170-260.

  2. "prefix lengths **14-25**, so genuine LPM" -- the conclusion survives and
     the figure does not. Lengths run 14-32. The tell is that 14-25 is 12
     lengths and the same sentence says 18 values; the missing length is /31,
     which no prefix in either trace uses.

  3. "**1,400 distinct prefixes**" for airtel2 -- right, and true of airtel1
     too, which nothing said.

None of the three was ever load-bearing, which is exactly why they survived: no
converter had been written yet, so nothing read them and nothing could
contradict them. How far off the stated range was is itself derived rather than
asserted here -- `render` counts it.

`plen_histogram` is the one table here that is EVIDENCE rather than description:
it is the D1 finding, rendered from the data, and the parser asserts the same
identity on every row it reads (`deltanet_trace.lpm_priority`).
"""

from __future__ import annotations

import collections
import hashlib
import os

from typing import Dict, List, Sequence

from util.raw_data import verify_raw
from bench.wl_deltanet.deltanet_topology import (
    EXTERNAL_PORT, derive_topology, homes)
from bench.wl_deltanet.deltanet_trace import (
    PRIORITY_BASE,
    PRIORITY_SLOPE,
    RAW,
    TRACES,
    Insert,
    collisions,
    edges,
    lpm_priority,
    read_trace,
)


HERE = os.path.dirname(os.path.abspath(__file__))
DOCUMENT = os.path.join(HERE, 'TRACES.md')

#: Figures PUBLISHED for this data set, from the Delta-net paper itself --
#: A. Horn, A. Kheradmand, M. R. Prasad, "Delta-net: Real-time Network
#: Verification Using Atoms", NSDI'17. They are not derived from the traces;
#: they are what a third party stated about them, which is why they live here
#: as named constants and are CHECKED against the derivation rather than
#: mixed into it (`test_deltanet_census.py`).
#:
#: Table 2 gives Airtel 1 and Airtel 2 as 68 nodes / 260 max links. Table 4
#: gives the "consistent data plane snapshot" extracted from ONOS as 38,100
#: rules, and §4.3.2 says of it: "except for the new Airtel data plane
#: snapshot where we pose 158 queries" -- the query count being the link
#: count. All three match `airtel1-only-inserts.csv` exactly.
PAPER_NODES = 68
PAPER_MAX_LINKS = 260
PAPER_SNAPSHOT_RULES = 38100
PAPER_SNAPSHOT_LINKS = 158
PAPER_PREFIXES = 1600
PAPER_SWITCHES = 16
PAPER_URL = 'https://github.com/delta-net/datasets'


def _digest(path: str) -> str:
    with open(path, 'rb') as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def trace_census(name: str, inserts: List[Insert]) -> Dict:
    """ Every number `TRACES.md` states about ONE trace, from that trace. """
    routers = {i.router for i in inserts}
    next_hops = {i.next_hop for i in inserts}
    per_router = collections.Counter(i.router for i in inserts)

    topology = derive_topology(inserts)
    homed = homes(inserts)
    per_home = collections.Counter(homed.values())

    return {
        'switches': len(topology.switches),
        'links': len(topology.links),
        'ports': sum(len(p) for p in topology.ports.values()),
        'degrees': {s: topology.degree(s) for s in topology.switches},
        'homing_switches': len(per_home),
        'prefixes_per_home': sorted(set(per_home.values())),
        'homes_nothing': sorted(set(topology.switches) - set(per_home)),
        'name': name,
        'sha256': _digest(os.path.join(RAW, name)),
        'inserts': len(inserts),
        'prefixes': len({i.prefix for i in inserts}),
        'routers': len(routers),
        'next_hops': len(next_hops),
        'names': len(routers | next_hops),
        'sinks': sorted(next_hops - routers),
        'sources': sorted(routers - next_hops),
        'edges': len(edges(inserts)),
        'collisions': collisions(inserts),
        'rules_per_router_min': min(per_router.values()),
        'rules_per_router_max': max(per_router.values()),
        'rules_per_router_mean': sum(per_router.values()) / len(per_router),
        'plen_histogram': dict(collections.Counter(i.plen for i in inserts)),
    }


def pair_census(left: List[Insert], right: List[Insert]) -> Dict:
    """ How the two traces differ -- the same network, routed two ways.

    They are not two samples of one thing: they share their prefix set exactly
    and differ only in where each router sends each prefix. That makes the pair
    a ready-made differential (CLOUD_BENCH_PLAN.md §2.3), so the overlap is
    measured rather than described.
    """
    lmap = {(i.router, i.prefix): i.next_hop for i in left}
    rmap = {(i.router, i.prefix): i.next_hop for i in right}
    shared = set(lmap) & set(rmap)

    def _same(field: str) -> bool:
        return ({getattr(i, field) for i in left}
                == {getattr(i, field) for i in right})

    return {
        'shared_keys': len(shared),
        'only_left': len(set(lmap) - set(rmap)),
        'only_right': len(set(rmap) - set(lmap)),
        'differing_next_hop': sum(1 for k in shared if lmap[k] != rmap[k]),
        # Measured as SET equality, not inferred from two equal counts: the
        # census reports 57 routers for both traces, and two 57-element sets
        # are not thereby the same 57 names.
        'same_prefixes': _same('prefix'),
        'same_routers': _same('router'),
        'same_next_hops': _same('next_hop'),
        'same_edges': (edges(left) == edges(right)),
    }


def census() -> Dict:
    """ Read the vendored traces -- after checking them -- and measure both. """
    verify_raw(RAW)
    traces = [(name, read_trace(os.path.join(RAW, name))) for name in TRACES]
    return {
        'traces': [trace_census(name, inserts) for name, inserts in traces],
        'pair': pair_census(traces[0][1], traces[1][1]),
    }


def _n(value: int) -> str:
    """ A count, in the plan's own thousands-separated spelling. """
    return '{:,}'.format(value)


def _table(header: Sequence[str], rows: Sequence[Sequence[str]],
           align: str = '') -> List[str]:
    align = align or 'l' * len(header)
    sep = {'l': '---', 'r': '---:', 'c': ':---:'}
    out = ['| ' + ' | '.join(header) + ' |',
           '|' + '|'.join(sep[a] for a in align) + '|']
    out.extend('| ' + ' | '.join(str(c) for c in row) + ' |' for row in rows)
    return out


def render(c: Dict) -> str:
    """ `TRACES.md`, from the census. """
    out: List[str] = []
    w = out.append
    first, second = c['traces']
    pair = c['pair']

    w('# The Delta-net traces — what the vendored data actually contains')
    w('')
    w('**GENERATED — do not edit.** Regenerate with `python3 -m')
    w('bench.wl_deltanet.deltanet_census` from `fave/`;')
    w('`test/test_deltanet_census.py` pins this file byte for byte against a')
    w('fresh derivation from `deltanet-traces/`. Scope, provenance and the')
    w('reason only two of the archive\'s eleven CSVs are here are in')
    w('[`deltanet-traces/README.md`](deltanet-traces/README.md), which states')
    w('what cannot be derived; everything below is derived.')
    w('')
    w('Background and the D1-D5 build plan: `CLOUD_BENCH_PLAN.md` §2.')
    w('')

    w('## The two traces')
    w('')
    out.extend(_table(
        ('trace', 'inserts', 'prefixes', 'routers', 'next-hops', 'names', 'edges'),
        [(t['name'], _n(t['inserts']), _n(t['prefixes']), t['routers'],
          t['next_hops'], t['names'], t['edges']) for t in c['traces']],
        align='lrrrrrr'))
    w('')
    w('"names" is the union of the router and next-hop columns: the two are')
    w('different sets, and §2.3\'s topology question is about the difference.')
    w('')
    out.extend(_table(('trace', 'sha256'),
                      [(t['name'], '`%s`' % t['sha256']) for t in c['traces']]))
    w('')

    w('## D1 — the fourth field is a priority encoding LPM')
    w('')
    w('    priority = %d * prefix_length + %d'
      % (PRIORITY_SLOPE, PRIORITY_BASE))
    w('')
    w('Exactly, on every row of both traces — **%s of %s**, no exception.'
      % (_n(first['inserts'] + second['inserts']),
         _n(first['inserts'] + second['inserts'])))
    w('Longer prefix, higher priority, which is how Delta-net and any')
    w('OpenFlow-style flat table linearise longest-prefix match into a')
    w('priority-ordered rule list.')
    w('')
    w('**The column therefore carries no information of its own** — everything')
    w('it states is already in the prefix. A converter reads the prefix and')
    w('ignores the column, and `deltanet_trace.parse_trace` asserts the')
    w('identity on every row so that a trace encoding something ELSE in that')
    w('field is refused rather than silently misread.')
    w('')
    w('The evidence, and at the same time the LPM depth profile:')
    w('')
    lengths = sorted(
        set(first['plen_histogram']) | set(second['plen_histogram']))
    out.extend(_table(
        ['prefix length', 'priority']
        + ['rules in %s' % t['name'].split('-')[0] for t in c['traces']],
        [['/%d' % plen, lpm_priority(plen)]
         + [_n(t['plen_histogram'].get(plen, 0)) for t in c['traces']]
         for plen in lengths],
        align='rr' + 'r' * len(c['traces'])))
    w('')
    w('%d lengths, %d..%d — **/31 is the one absent**, which is why the field'
      % (len(lengths), min(lengths), max(lengths)))
    w('takes %d distinct values over a %d-length span and not %d.'
      % (len(lengths), max(lengths) - min(lengths) + 1,
         max(lengths) - min(lengths) + 1))
    w('')

    w('### Three figures this replaces')
    w('')
    w('All three were measured by hand at vendoring time and stated in')
    w('`deltanet-traces/README.md` and `CLOUD_BENCH_PLAN.md` §2:')
    w('')
    out.extend(_table(
        ('stated', 'derived', 'what happened'),
        [('fourth field takes 18 values in **180-220**',
          '18 values in **%d-%d**' % (lpm_priority(min(lengths)),
                                      lpm_priority(max(lengths))),
          'the count was right, the range was not'),
         ('prefix lengths **14-25**',
          '**%d-%d**' % (min(lengths), max(lengths)),
          '14-25 is 12 lengths, and the same sentence says 18 values'),
         ('**%s** prefixes (airtel2)' % _n(second['prefixes']),
          '**%s**, and airtel1 the same' % _n(second['prefixes']),
          'right, but stated of one trace only')]))
    w('')
    w('Nothing read them, which is why nothing caught them: no converter')
    w('existed yet. Had D1 been guessed from the stated `180-220` instead of')
    w('measured, the guess would have placed %d of the %d actual priorities'
      % (sum(1 for plen in lengths if not 180 <= lpm_priority(plen) <= 220),
         len(lengths)))
    w('outside its own range.')
    w('')

    w('## The names, and what is not a router')
    w('')
    w('Names are `s<i>-<j>`. The router column and the next-hop column do not')
    w('span the same set, and both asymmetries are a modelling decision for D3')
    w('rather than a defect:')
    w('')
    out.extend(_table(
        ('trace', 'routers', 'next-hops', 'union',
         'next-hops with NO rules', 'routers no-one forwards to'),
        [(t['name'], t['routers'], t['next_hops'], t['names'],
          len(t['sinks']), len(t['sources'])) for t in c['traces']],
        align='lrrrrr'))
    w('')
    w('A next-hop carrying no rules of its own is a **sink**: a packet')
    w('forwarded there reaches a device with an empty table. In `%s` they are'
      % first['name'])
    w('')
    w('    %s' % ' '.join(first['sinks']))
    w('')
    w('and what the model should do with them — drop, treat as an egress')
    w('edge port, or refuse the trace — is D3, not D2.')
    w('')
    w('**Interfaces are absent entirely.** A row names a router and a next-hop')
    w('and neither end\'s port, while FaVe\'s router model is port-based. That,')
    w('not the fourth column, is the converter\'s real open question.')
    w('')

    w('## Replay is order-independent — the trace has no update semantics')
    w('')
    out.extend(_table(
        ('trace', 'inserts', 'distinct (router, prefix)', 'overwrites'),
        [(t['name'], _n(t['inserts']), _n(t['inserts'] - t['collisions']),
          t['collisions']) for t in c['traces']],
        align='lrrr'))
    w('')
    w('No insert ever overwrites a `(router, prefix)` an earlier one set, and')
    w('the files contain no withdrawal (the parser refuses one). So no rule')
    w('supersedes another, replay order cannot matter, and **the final FIB is')
    w('the file**. §2.1 planned D2 as a replay; the measurement makes it a')
    w('census.')
    w('')
    w('It also bounds what D5 can claim. An insert-only, collision-free trace')
    w('measures incremental FIB *construction*, never churn: nothing is')
    w('withdrawn and nothing is revised. The archive members that would test')
    w('churn are not in the repository (§2).')
    w('')

    w('## The two traces are one network routed two ways')
    w('')
    w('Identical as SETS, not merely equal in count — measured that way')
    w('because two %d-element sets are not thereby the same %d names:'
      % (first['routers'], first['routers']))
    w('')
    out.extend(_table(
        ('the two traces agree on', 'identical'),
        [('the %s prefixes' % _n(first['prefixes']),
          'yes' if pair['same_prefixes'] else 'NO'),
         ('the %d router names' % first['routers'],
          'yes' if pair['same_routers'] else 'NO'),
         ('the %d next-hop names' % first['next_hops'],
          'yes' if pair['same_next_hops'] else 'NO'),
         ('the directed edge set',
          'yes' if pair['same_edges'] else
          'NO — %d vs %d' % (first['edges'], second['edges']))],
        align='lc'))
    w('')
    w('The edge set is the one that differs, and that IS the routing change.')
    w('Per rule:')
    w('')
    out.extend(_table(
        ('', 'rules'),
        [('`(router, prefix)` keys in both', _n(pair['shared_keys'])),
         ('… of those, a DIFFERENT next-hop', _n(pair['differing_next_hop'])),
         ('keys only in %s' % first['name'], _n(pair['only_left'])),
         ('keys only in %s' % second['name'], _n(pair['only_right']))],
        align='lr'))
    w('')
    w('So the pair is a ready-made **differential**: one topology, one prefix')
    w('set, two forwarding states, and every reachability difference between')
    w('them is attributable to the routing change alone. It is a sharper')
    w('cross-engine test than either snapshot on its own — three engines')
    w('agreeing on one model is weaker evidence than three engines agreeing on')
    w('the DELTA between two. `CLOUD_BENCH_PLAN.md` §2.3.')
    w('')

    w('## D3 — the ports are in the data')
    w('')
    w('`s<i>-<j>` is not a router. It is a **(switch, port) pair**, which is')
    w('the paper\'s own device: Delta-net splits one switch into a graph node')
    w('per input port its rules match, "if a switch s contains rules that can')
    w('match three input ports, we encode s as three separate nodes" (§4.1).')
    w('So both columns of every row name a port, and a port-annotated topology')
    w('comes out of the traces with nothing invented:')
    w('')
    out.extend(_table(
        ('trace', 'switches', 'inter-switch links', 'ports'),
        [(t['name'], t['switches'], t['links'], t['ports'])
         for t in c['traces']],
        align='lrrr'))
    w('')
    w('**Every switch has exactly `degree + 1` ports** — one per neighbour,')
    w('plus port %d, which no inter-switch link ever lands on. That is the'
      % EXTERNAL_PORT)
    w('external, border-router-facing port (the paper connects each of the')
    w('%d Open vSwitches to a Quagga border router), and it is where traffic'
      % PAPER_SWITCHES)
    w('enters the modelled network.')
    w('')
    w('The invariants that make the model exact, all measured and all REFUSED')
    w('by `deltanet_topology.py` rather than assumed — each is a property of')
    w('these two files, not of the format:')
    w('')
    out.extend(_table(
        ('invariant', 'why FaVe needs it'),
        [('the destination port is a function of the switch PAIR',
          'one link per pair, so a neighbour always lands on one port'),
         ('distinct neighbours occupy distinct ports',
          'the port identifies the link, so the map inverts'),
         ('the switch-level edge set is symmetric',
          '**this is what recovers the EGRESS port**, which no row states'),
         ('ports are exactly 1..degree+1', 'no port is unaccounted for'),
         ('no rule forwards within a switch, or back out its ingress port',
          'neither has a FaVe counterpart')]))
    w('')
    w('The egress port is the one figure a row genuinely does not carry, and')
    w('it does not need to: the port `i` sends out of to reach `k` is the port')
    w('`i` receives from `k` on, and symmetry makes that total. So the')
    w('converter has no interface to invent — which is the opposite of what')
    w('D3 was filed believing.')
    w('')
    w('### Where traffic leaves')
    w('')
    w('A reachability property needs an egress as well as an ingress. A')
    w('prefix\'s rules thin towards one switch and stop; the node that')
    w('RECEIVES a prefix while carrying no rule for it is where it is')
    w('delivered. Every one of the %s prefixes terminates at exactly one'
      % _n(first['prefixes']))
    w('switch, and **%d switches home %s prefixes each**:'
      % (first['homing_switches'],
         ' or '.join(str(v) for v in first['prefixes_per_home'])))
    w('')
    w('    %s x %s = %s'
      % (first['homing_switches'],
         ' or '.join(str(v) for v in first['prefixes_per_home']),
         _n(first['prefixes'])))
    w('')
    w('which is the paper\'s "each border router advertises one hundred IP')
    w('prefixes" (§4.2) — and it accounts for the %s-versus-%s prefix gap'
      % (_n(PAPER_PREFIXES), _n(first['prefixes'])))
    w('recorded below: switches %s home nothing, and the shortfall is exactly'
      % ' and '.join('s%d' % s for s in first['homes_nothing']))
    w('%d x %s. They are well connected (degree %s) but not the best connected'
      % (len(first['homes_nothing']),
         ' or '.join(str(v) for v in first['prefixes_per_home']),
         ' and '.join(str(first['degrees'][s])
                      for s in first['homes_nothing'])))
    w('(s%d has degree %d and homes its hundred), so "pure transit" describes'
      % (max(first['degrees'], key=lambda s: first['degrees'][s]),
         max(first['degrees'].values())))
    w('what they do here rather than explaining why.')
    w('')
    w('**Both traces derive the SAME topology** — same switches, same links,')
    w('same port map, same homing. Only the forwarding differs, which is what')
    w('makes §2.3\'s differential a clean one.')
    w('')

    w('## Checked against the paper that published the data set')
    w('')
    w('Horn, Kheradmand and Prasad, *Delta-net: Real-time Network')
    w('Verification Using Atoms*, NSDI\'17 — Table 2, Table 4 and §4.3.2.')
    w('These figures are NOT derived from the traces; they are what a third')
    w('party stated about them, so they are held as named constants and')
    w('compared, never blended into the derivation.')
    w('')
    out.extend(_table(
        ('the paper states', 'published', 'derived here', 'agrees'),
        [('nodes (Table 2)', PAPER_NODES, first['names'],
          'yes' if first['names'] == PAPER_NODES else 'NO'),
         ('rules in the ONOS data-plane snapshot (Table 4)',
          _n(PAPER_SNAPSHOT_RULES), _n(first['inserts']),
          'yes' if first['inserts'] == PAPER_SNAPSHOT_RULES else 'NO'),
         ('queries posed on that snapshot, = its links (§4.3.2)',
          PAPER_SNAPSHOT_LINKS, first['edges'],
          'yes' if first['edges'] == PAPER_SNAPSHOT_LINKS else 'NO')],
        align='lrrc'))
    w('')
    w('**All three identify `%s` as the very snapshot §4.3.2 reports on.**'
      % first['name'])
    w('That is a stronger footing than the workload was planned to have: the')
    w('MODEL is now corroborated by a published third-party description, even')
    w('though no reachability VERDICT is (see below).')
    w('')
    w('`%s` matches on rules and nodes and carries **%d** links, not %d. The'
      % (second['name'], second['edges'], PAPER_SNAPSHOT_LINKS))
    w('paper publishes one snapshot, so nothing states what its edge count')
    w('should be; §2.3 is where that difference is put to use.')
    w('')
    w('Two figures do NOT line up, and are recorded rather than reconciled:')
    w('')
    out.extend(_table(
        ('the paper states', 'published', 'derived here'),
        [('unique IP prefixes advertised (§4.2)', _n(PAPER_PREFIXES),
          _n(first['prefixes'])),
         ('max links in the topology (Table 2)', PAPER_MAX_LINKS,
          first['edges'])],
        align='lrr'))
    w('')
    w('The first is **accounted for, not resolved**, by the homing above: %d'
      % PAPER_SWITCHES)
    w('switches advertising 100 prefixes each gives the paper\'s "%s unique'
      % _n(PAPER_PREFIXES))
    w('(but possibly overlapping)", the traces home %s at %d switches, and %s'
      % (_n(first['prefixes']), first['homing_switches'],
         ' and '.join('s%d' % s for s in first['homes_nothing'])))
    w('home none. So the gap is exactly those two switches\' hundreds. WHY')
    w('they have none — no border router attached, nothing advertised, or a')
    w('distillation that dropped them — the data does not say.')
    w('')
    w('The second is not a discrepancy at all: %d is the topology\'s capacity'
      % PAPER_MAX_LINKS)
    w('and %d is how many node-level edges this snapshot\'s rules use, over'
      % first['edges'])
    w('%d inter-switch links.' % first['links'])
    w('')
    w('The paper also settles two things this repository recorded as unknown:')
    w('the data set\'s home, `%s` (reference [14]) —' % PAPER_URL)
    w('`deltanet-traces/README.md` had the download URL as never recorded —')
    w('and the `s<i>-<j>` naming. The topology is AS 9498 (Airtel) emulated as')
    w('**%d Open vSwitches**, and the paper splits a switch into several graph'
      % PAPER_SWITCHES)
    w('nodes when its rules match on several input ports ("we report the number')
    w('of graph nodes rather than the number of switches"). So `i` is the')
    w('switch and `j` the per-input-port node, %d switches becoming %d nodes,'
      % (PAPER_SWITCHES, PAPER_NODES))
    w('and the sinks above are graph nodes that terminate a link without')
    w('carrying rules of their own.')
    w('')

    w('## What the data does not contain')
    w('')
    w('Pure L3 forwarding: no ACLs, no rewrites, no transport fields. Any')
    w('compliance property has to be invented, so this workload is a reuse of')
    w('the DATA and not a reproduction of the EXPERIMENT — §2.1 says so.')
    w('')
    w('**The distinction the section above sharpens: the MODEL is externally')
    w('corroborated, the VERDICTS are not.** The paper states how many rules,')
    w('nodes and links this snapshot has, and the derivation matches all three,')
    w('so a mis-parse of the traces would now be caught by something outside')
    w('this repository. It publishes no reachability answer — its own results')
    w('are query TIMES (Table 4), not sat/unsat — so every correctness result')
    w('from this workload remains a consensus between implementations in this')
    w('tree. That is §0\'s first gap, and only `wl_cloud` closes it. A result')
    w('here must not be written as though the paper had blessed it.')
    w('')
    return '\n'.join(out) + '\n'


def build() -> str:
    """ Read the raw traces and render the document. """
    return render(census())


def main() -> None:
    document = build()
    with open(DOCUMENT, 'w') as handle:
        handle.write(document)
    print("wrote %s (%d bytes)" % (DOCUMENT, len(document)))


if __name__ == '__main__':
    main()
