#!/usr/bin/env python3

# -*- coding: utf-8 -*-

# Generated by CodiumAI

# This file is part of Policy Translator.

# Policy Translator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Policy Translator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Policy Translator.  If not, see <https://www.gnu.org/licenses/>.


import pytest
import pyparsing as pp

from unittest.mock import patch
from fpl_grammar import parse_fpl, print_prosa

class TestCodeUnderTest:


    # Successfully parse a simple FPL policy
    def test_parse_simple_fpl_policy(self):
        raw_policy = "def role Servers\n\tipv6 = 2001:db8::100/120\nend"
        expected_result = [['role', 'Servers', [['ipv6', '2001:db8::100/120']]]]
    
        result = parse_fpl(raw_policy)
    
        assert result == expected_result

    # Fail to parse an empty FPL policy
    def test_fail_to_parse_empty_fpl_policy(self):
        raw_policy = ""
    
        with pytest.raises(pp.ParseException):
            parse_fpl(raw_policy)

    # Successfully parse a FPL policy with comments
    def test_parse_fpl_policy_with_comments(self):
        raw_policy = "# This is a comment\n\ndef role Servers\n\tipv6 = 2001:db8::100/120\nend"
        expected_result = [['role', 'Servers', [['ipv6', '2001:db8::100/120']]]]

        result = parse_fpl(raw_policy)

        assert result == expected_result

    # Successfully parse a FPL policy with quoted values
    def test_parse_fpl_policy_with_quoted_values(self):
        raw_policy = "def role Servers\n\tipv6 = '2001:db8::100/120'\nend"
        expected_result = [['role', 'Servers', [['ipv6', "'2001:db8::100/120'"]]]]

        result = parse_fpl(raw_policy)

        assert result == expected_result

    # Successfully parse a complex FPL policy
    def test_parse_complex_fpl_policy(self):
        raw_policy = "def role Servers\n\tincludes WebServers\n\toffers SSH\n\tipv6 = 2001:db8::100/120\nend\n\ndesc service ICMP\n\tprotocol = 'icmp'\nend\n\ndesc service SSH\n\tprotocol = 'tcp'\n\tport = 22\nend"
        expected_result = [['role', 'Servers', [['includes', 'WebServers'], ['offers', 'SSH'], ['ipv6', '2001:db8::100/120']]], ['service', 'ICMP', [['protocol', 'icmp']]], ['service', 'SSH', [['protocol', 'tcp'], ['port', '22']]]]

        result = parse_fpl(raw_policy)

        assert result == expected_result

    # Successfully parse a FPL policy with lists
    def test_parse_fpl_policy_with_lists(self):
        raw_policy = "def role Intern\n\thosts = ['cluster.cs.uni-potsdam.de', 'printer.cs.uni-potsdam.de']\n\tvlan = 6\nend"
        expected_result = [['role', 'Intern', [['hosts', ['cluster.cs.uni-potsdam.de', 'printer.cs.uni-potsdam.de']], ['vlan', '6']]]]

        result = parse_fpl(raw_policy)

        assert result == expected_result

    # Successfully parse a FPL policy with nested roles
    def test_parse_fpl_policy_with_nested_roles(self):
        raw_policy = "def role Servers\n\tincludes WebServers\n\toffers SSH\n\tipv6 = 2001:db8::100/120\nend"
        expected_result = [['role', 'Servers', [['includes', 'WebServers'], ['offers', 'SSH'], ['ipv6', '2001:db8::100/120']]]]

        result = parse_fpl(raw_policy)

        assert result == expected_result

    # Successfully parse a FPL policy with nested services
    def test_parse_nested_services(self):
        raw_policy = "def role Servers\n\tincludes WebServers\n\toffers SSH\n\tipv6 = 2001:db8::100/120\nend\n\ndesc service SSH\n\tprotocol = 'tcp'\n\tport = 22\nend"
        expected_result = [['role', 'Servers', [['includes', 'WebServers'], ['offers', 'SSH'], ['ipv6', '2001:db8::100/120']]], ['service', 'SSH', [['protocol', 'tcp'], ['port', '22']]]]

        result = parse_fpl(raw_policy)

        assert result == expected_result

    # Successfully parse a FPL policy with default policy set to allow
    def test_parse_simple_fpl_policy(self):
        raw_policy = "def role Servers\n\tipv6 = 2001:db8::100/120\nend"
        expected_result = [['role', 'Servers', [['ipv6', '2001:db8::100/120']]]]

        result = parse_fpl(raw_policy)

        assert result == expected_result

    # Successfully parse a FPL policy with default policy set to deny
    def test_parse_fpl_with_default_deny(self):
        raw_policy = "define policies(default: deny)\nend"
        expected_result = [['policies', [['default_rule', 'deny']]]]

        result = parse_fpl(raw_policy)

        assert result == expected_result

    # Successfully parse a FPL policy with multiple policies
    def test_parse_multiple_policies(self):
        raw_policy = "def role Servers\n\tipv6 = 2001:db8::100/120\nend\n\ndef role Clients\n\tipv4 = 192.168.0.0/24\nend"
        expected_result = [['role', 'Servers', [['ipv6', '2001:db8::100/120']]], ['role', 'Clients', [['ipv4', '192.168.0.0/24']]]]

        result = parse_fpl(raw_policy)

        assert result == expected_result

    # Fail to parse a FPL policy with a missing end statement
    def test_fail_to_parse_missing_end_statement(self):
        raw_policy = "def role Servers\n\tipv6 = 2001:db8::100/120"
    
        with pytest.raises(pp.ParseException):
            parse_fpl(raw_policy)

    # Fail to parse a FPL policy with an invalid definition statement
    def test_fail_to_parse_invalid_definition_statement(self):
        raw_policy = "def role Servers\n\tipv6 = 2001:db8::100/120\n"
        with pytest.raises(pp.ParseException):
            parse_fpl(raw_policy)

    # Fail to parse a FPL policy with an invalid role name
    def test_fail_to_parse_invalid_role_name(self):
        raw_policy = "def role 123\n\tipv6 = 2001:db8::100/120\nend"
    
        with pytest.raises(pp.ParseException):
            parse_fpl(raw_policy)

    # Fail to parse a FPL policy with an invalid service name
    def test_fail_to_parse_invalid_service_name(self):
        raw_policy = "def role Servers\n\tipv6 = 2001:db8::100/120\nend"
        with pytest.raises(pp.ParseException):
            parse_fpl(raw_policy)

    # Fail to parse a FPL policy with an invalid operator
    def test_fail_to_parse_invalid_operator(self):
        raw_policy = "def role Servers\n\tipv6 = 2001:db8::100/120\nend"
        with pytest.raises(pp.ParseException):
            parse_fpl(raw_policy)

    # Fail to parse a FPL policy with an invalid port number
    def test_fail_to_parse_policy_with_invalid_port_number(self):
        raw_policy = "def role Servers\n\tport = abc\nend"
    
        with pytest.raises(pp.ParseException):
            parse_fpl(raw_policy)

    # Fail to parse a FPL policy with an invalid protocol
    def test_fail_to_parse_invalid_protocol(self):
        raw_policy = "def role Servers\n\tprotocol = 'invalid'\nend"
    
        with pytest.raises(pp.ParseException):
            parse_fpl(raw_policy)

    # Test the print_prosa function output for a simple FPL policy
    def test_print_prosa_simple_fpl_policy(self):
        raw_policy = "def role Servers\n\tipv6 = 2001:db8::100/120\nend"
        expected_output = "The role Servers has the attributes ipv6=2001:db8::100/120."
    
        # Mock the print function
        import builtins
        original_print = builtins.print
        builtins.print = lambda *args, **kwargs: None
    
        # Call the function under test
        print_prosa(parse_fpl(raw_policy))
    
        # Restore the print function
        builtins.print = original_print
    
        # Capture the printed output
        import sys
        captured_output = sys.stdout.getvalue().strip()
    
        assert captured_output == expected_output

    # Test the print_prosa function output for a complex FPL policy
    def test_print_prosa_complex_fpl_policy(self):
        raw_policy = "def role Servers\n\tincludes WebServers\n\toffers SSH\n\tipv6 = 2001:db8::100/120\nend\n\ndesc service ICMP\n\tprotocol = 'icmp'\nend\n\ndesc service SSH\n\tprotocol = 'tcp'\n\tport = 22\nend\n\ndefine policies(default: deny)\n\tClients <->> WebServer.HTTP\nend"
        expected_output = "The role Servers includes the roles WebServers and offers the services SSH. The role Servers has the attributes ipv6=2001:db8::100/120.\nThe service ICMP has the attributes protocol=icmp.\nThe service SSH has the attributes protocol=tcp and port 22.\nThe policy defines policies(default: deny) and has the rule Clients <->> WebServer.HTTP.\n"

        with patch('builtins.print') as mock_print:
            print_prosa(parse_fpl(raw_policy))
            mock_print.assert_called_with(expected_output)
