#!/usr/bin/env python3

# -*- coding: utf-8 -*-

# Copyright 2026 Claas Lorenz <claas_lorenz@genua.de>

# This file is part of FaVe.

# FaVe is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# FaVe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with FaVe.  If not, see <https://www.gnu.org/licenses/>.

""" Reader for the NoD cloud dataset's own inventory (CLOUD_BENCH_PLAN.md §1.9).

`cloud-tf/README.txt` is not documentation beside the data -- it IS the
dataset's inventory and its policy. It declares 25 services with their address
prefixes, and a 26x26 authorisation matrix over them. That matrix is the
workload's FPL policy, and this module is what turns it into one.

IT IS PARSED, NEVER TRANSCRIBED. §1.9.5 left the choice open -- parse the
matrix mechanically, or write the FPL by hand and check it against the README.
Parsing is the only one of the two that satisfies §1.8: 676 matrix cells copied
by eye is `oracle.json`'s original defect at a hundred times the scale, and a
single flipped cell would turn into a wrong expectation that FaVe then agrees
with. Everything this module returns comes out of the file; nothing is defaulted.

**The service algebra, MEASURED against `network.tf` and pinned by
`test/test_cloud_readme.py`.** The README states a "Public TCP port: 331" and
lists 25 services; it does not state the relation between them. Counting the
2,941 rules' port constraints gives exactly the 25 values 331..355, and the 19
gateway NAT rules map `121.140.254.<i>:331+i` onto the datacenter the README
says hosts service `i`. So:

    service i  <->  TCP port 331 + i  <->  public address 121.140.254.i

which is `service_port` and `service_address` below. This also settles the
"open discrepancy" §1.4 recorded against the oracle -- that the README names 331
public while query 03 is satisfiable on 332. 331 is not *the* public port, it is
the BASE of the service port range: 331 is service 0 and 332 is service 1, and
query 03's target sits in datacenter 1, whose only service is 1. There is no
off-by-one and the scenarios were not generated by different runs.

**The 26th index is the Internet, CONFIRMED from the data** (§1.9.5's second
open question, which asked for exactly this and forbade assuming it). The
matrix is 26 wide but only services 0-24 are declared. Three independently
derived sets coincide exactly:

  * matrix row 25 -- the services index 25 may reach;
  * the 43 ACL rules carrying NO source constraint, i.e. reachable from anywhere;
  * the 19 destination-NAT rules at the internet gateway.

all three being {0, 1, 8, 10, 11, 13, 14, 18, 19, 22, 23}. `Internet` is
therefore a role the DATASET NAMES, not one fabricated to make the policy
expressible -- which is what lets this workload's policy be third-party
evidence rather than self-derived. `test_cloud_readme.py` asserts the
coincidence against `network.tf`, so the reading cannot rot.
"""

from __future__ import annotations

import re

from typing import Any, Dict, List, Optional, Sequence


class ReadmeParseError(Exception):
    """ A README this module will not guess about. """


#: The base of the service port range -- read out of the file, never assumed.
#: Kept as a name because two derivations depend on it (`SERVICE_PORT` and
#: `service_address`) and a bare 331 in either would hide that.
_PUBLIC_PORT_KEY = 'Public TCP port'
_PUBLIC_IP_KEY = 'Public services IP'

#: Index 25 in a 26-wide matrix over 25 declared services. Confirmed against
#: `network.tf`, not assumed -- see the module docstring.
INTERNET_INDEX = 25

_SCALARS = {
    'Datacenter tree height': 'tree_height',
    _PUBLIC_IP_KEY: 'public_ip',
    _PUBLIC_PORT_KEY: 'public_port',
    'Number of hosts per leaf router': 'hosts_per_leaf',
    'Number of leaf routers': 'leaf_routers',
    'Number of bits of leaf IPs': 'leaf_ip_bits',
    'Number of bits per datacenter': 'datacenter_bits',
    'Router branching': 'router_branching',
}

_INT_SCALARS = frozenset(_SCALARS.values()) - {'public_ip'}

_SERVICE_IP = re.compile(r'^Service (\d+): #(\d+) (.+)$')
_DC_SERVICES = re.compile(r'^Datacenter (\d+): #(\d+) \[([^\]]*)\]$')
_DC_BLOCK = re.compile(r'^Datacenter (\d+): (\S+) \(port (\d+)\)$')
_ROUTER_SERVICES = re.compile(r'^Services of router (\d+): set\(\[([^\]]*)\]\)$')
_MATRIX_ROW = re.compile(r'^(\d+): ([01]+)$')
_INTERNET_PORT = re.compile(r'^Internet port: (\d+)$')
_PREFIX = re.compile(r'^\d+\.\d+\.\d+\.\d+/\d+$')


def _ints(text: str) -> List[int]:
    return [int(t) for t in text.replace(',', ' ').split()]


class CloudReadme:
    """ Everything `cloud-tf/README.txt` states, in structured form.

    Attributes:
        scalars: the generator's stated parameters (`public_ip`, `public_port`,
            `hosts_per_leaf`, ...).
        services: {index: [prefix, ...]} from the "Services' IPs" table.
        matrix: the 26x26 ACL matrix as a list of lists of 0/1 ints.
        datacenter_services: {dc: [service index, ...]}.
        datacenter_block: {dc: (address, core node id)}.
        router_services: {leaf ingress node id: [service index, ...]}.
        internet_port: the internet gateway's node id.
    """

    __slots__ = (
        'scalars', 'services', 'matrix', 'datacenter_services',
        'datacenter_block', 'router_services', 'internet_port',
    )

    def __init__(self, **kwargs: Any) -> None:
        for slot in self.__slots__:
            setattr(self, slot, kwargs[slot])

    # -- the derived algebra -------------------------------------------------

    @property
    def service_port_base(self) -> int:
        return int(self.scalars['public_port'])

    def service_port(self, service: int) -> int:
        """ TCP port of service `service`. See the module docstring. """
        self._known(service)
        return self.service_port_base + service

    def service_address(self, service: int) -> str:
        """ Public address of service `service`, `<public ip base> + service`.

        The gateway's 19 DNAT rules are `121.140.254.<i>:331+i`, so the two
        offsets are the same index and neither is free to drift.
        """
        self._known(service)
        octets = [int(o) for o in self.scalars['public_ip'].split('.')]
        octets[3] += service
        if octets[3] > 255:
            raise ReadmeParseError(
                "service %d's public address runs past %s: the README's "
                "'%s' cannot be a per-service base here"
                % (service, self.scalars['public_ip'], _PUBLIC_IP_KEY))
        return '.'.join(str(o) for o in octets)

    def _known(self, service: int) -> None:
        if service not in self.services:
            raise ReadmeParseError(
                "service %r is not declared; the README declares %d..%d"
                % (service, min(self.services), max(self.services)))

    @property
    def internet_index(self) -> int:
        """ The one matrix index that is not a declared service.

        DERIVED, so the parser stays a parser: `_validate` has already
        established that the matrix is square and exactly one wider than the
        service table, which leaves precisely one undeclared index and puts it
        last. `INTERNET_INDEX` is this dataset's value of it, pinned by
        `test_cloud_readme.py` rather than assumed here -- a module constant
        that also acted as a precondition would have made the reader reject
        every scenario but `cloud/base`.
        """
        return len(self.services)

    @property
    def roles(self) -> List[int]:
        """ Every matrix index: the 25 declared services plus the Internet. """
        return list(range(len(self.matrix)))

    def permits(self, source: int, target: int) -> bool:
        """ Does the matrix authorise `source` to reach `target`'s service? """
        return self.matrix[source][target] == 1

    def authorised_pairs(self) -> List[tuple]:
        """ Every ordered 1-cell, in row-major order.

        Ordered, not unordered, although the matrix is symmetric: the two
        directions of a pair are INDEPENDENT flows in the data plane, each
        carrying its own destination port, so each is its own policy rule.
        """
        return [
            (i, j) for i in self.roles for j in self.roles
            if self.matrix[i][j] == 1
        ]


def parse_readme(text: str) -> CloudReadme:
    """ `cloud-tf/README.txt` -> a `CloudReadme`.

    Refuses rather than guesses. The README has two sections that both open
    their lines with `Datacenter <n>:` under different meanings -- the service
    census and the address block -- so parsing is section-aware and a line
    matching neither shape in the section it appears in is an error, not a
    skip. A silently skipped line is how a partial matrix would get in.
    """
    scalars: Dict[str, Any] = {}
    services: Dict[int, List[str]] = {}
    matrix_rows: Dict[int, List[int]] = {}
    datacenter_services: Dict[int, List[int]] = {}
    datacenter_block: Dict[int, Any] = {}
    router_services: Dict[int, List[int]] = {}
    internet_port: Optional[int] = None

    section = 'preamble'

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith('$'):
            continue

        if line == 'Services per Datacenter:':
            section = 'dc_services'
            continue
        if line == "Services' IPs:":
            section = 'service_ips'
            continue
        if line == 'ACL Matrix:':
            section = 'matrix'
            continue

        # The trailing section has no header of its own: it starts at the first
        # `Datacenter <n>: <addr> (port <id>)`, which is why that shape is
        # tested before the section's own line shapes.
        block = _DC_BLOCK.match(line)
        if block:
            section = 'blocks'
            datacenter_block[int(block.group(1))] = (
                block.group(2), int(block.group(3)))
            continue

        if section == 'preamble':
            key, _, value = line.partition(':')
            if key not in _SCALARS:
                raise ReadmeParseError(
                    "unrecognised preamble line %r. Refused rather than "
                    "skipped: a parameter this module does not know about may "
                    "be one a later derivation needs." % line)
            name = _SCALARS[key]
            scalars[name] = int(value) if name in _INT_SCALARS else value.strip()

        elif section == 'dc_services':
            match = _DC_SERVICES.match(line)
            if not match:
                raise ReadmeParseError(
                    "%r is not a datacenter service census" % line)
            listed = _ints(match.group(3))
            if len(listed) != int(match.group(2)):
                raise ReadmeParseError(
                    "datacenter %s claims #%s services and lists %d"
                    % (match.group(1), match.group(2), len(listed)))
            datacenter_services[int(match.group(1))] = listed

        elif section == 'service_ips':
            match = _SERVICE_IP.match(line)
            if not match:
                raise ReadmeParseError("%r is not a service address line" % line)
            prefixes = [p.strip() for p in match.group(3).split(',')]
            if len(prefixes) != int(match.group(2)):
                raise ReadmeParseError(
                    "service %s claims #%s prefixes and lists %d"
                    % (match.group(1), match.group(2), len(prefixes)))
            for prefix in prefixes:
                if not _PREFIX.match(prefix):
                    raise ReadmeParseError(
                        "service %s carries %r, which is not a CIDR prefix"
                        % (match.group(1), prefix))
            services[int(match.group(1))] = prefixes

        elif section == 'matrix':
            match = _MATRIX_ROW.match(line)
            if not match:
                raise ReadmeParseError("%r is not an ACL matrix row" % line)
            matrix_rows[int(match.group(1))] = [int(c) for c in match.group(2)]

        elif section == 'blocks':
            router = _ROUTER_SERVICES.match(line)
            if router:
                router_services[int(router.group(1))] = _ints(router.group(2))
                continue
            internet = _INTERNET_PORT.match(line)
            if internet:
                internet_port = int(internet.group(1))
                continue
            raise ReadmeParseError("%r is not a router or internet line" % line)

    return _validate(
        scalars, services, matrix_rows, datacenter_services,
        datacenter_block, router_services, internet_port,
    )


def _validate(
        scalars: Dict[str, Any],
        services: Dict[int, List[str]],
        matrix_rows: Dict[int, List[int]],
        datacenter_services: Dict[int, List[int]],
        datacenter_block: Dict[int, Any],
        router_services: Dict[int, List[int]],
        internet_port: Optional[int],
) -> CloudReadme:
    """ Every cross-check the README can answer on its own.

    None of these is defensive dressing: each one is a way the file could be
    read plausibly-but-wrongly, and the matrix's width against the service
    count is the one that §1.9.5 asked to have settled.
    """
    missing = sorted(set(_SCALARS.values()) - set(scalars))
    if missing:
        raise ReadmeParseError(
            "the README states no %s" % ', '.join(missing))

    if internet_port is None:
        raise ReadmeParseError("the README states no internet port")

    if sorted(services) != list(range(len(services))):
        raise ReadmeParseError(
            "the service indices are not contiguous from 0: %s"
            % sorted(services))

    if sorted(matrix_rows) != list(range(len(matrix_rows))):
        raise ReadmeParseError(
            "the ACL matrix rows are not contiguous from 0: %s"
            % sorted(matrix_rows))

    matrix = [matrix_rows[i] for i in sorted(matrix_rows)]
    width = {len(row) for row in matrix}
    if width != {len(matrix)}:
        raise ReadmeParseError(
            "the ACL matrix is %d rows of width(s) %s: not square"
            % (len(matrix), sorted(width)))

    # THE §1.9.5 QUESTION, answered here rather than assumed at the call site.
    # 26 indices over 25 declared services: the extra one is the Internet, and
    # it must be the LAST, because every other index is a service index used
    # directly as a row number.
    if len(matrix) != len(services) + 1:
        raise ReadmeParseError(
            "the ACL matrix is %dx%d over %d declared services. This module "
            "reads the one undeclared index as the Internet (§1.9.5), which "
            "only holds for exactly one extra index."
            % (len(matrix), len(matrix), len(services)))

    declared = set(services)
    for datacenter, listed in datacenter_services.items():
        unknown = sorted(set(listed) - declared)
        if unknown:
            raise ReadmeParseError(
                "datacenter %d hosts undeclared service(s) %s"
                % (datacenter, unknown))
    for router, listed in router_services.items():
        unknown = sorted(set(listed) - declared)
        if unknown:
            raise ReadmeParseError(
                "router %d serves undeclared service(s) %s" % (router, unknown))

    return CloudReadme(
        scalars=scalars,
        services=services,
        matrix=matrix,
        datacenter_services=datacenter_services,
        datacenter_block=datacenter_block,
        router_services=router_services,
        internet_port=internet_port,
    )


def read_readme(path: str) -> CloudReadme:
    """ `parse_readme` on a file. """
    with open(path, 'r') as readme:
        return parse_readme(readme.read())
