#!/usr/bin/env python3

# -*- coding: utf-8 -*-

# Copyright 2026 Claas Lorenz <claas_lorenz@genua.de>

# This file is part of FaVe.

# FaVe is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# FaVe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with FaVe.  If not, see <https://www.gnu.org/licenses/>.

""" What wl_cloud actually contains: the workload census, DERIVED (`WORKLOAD.md`).

The question this answers is the one asked of every benchmark -- how many
devices of which type, what topology, how many ACL and forwarding rules, which
header fields -- and the reason it is a module rather than a section of prose is
CLOUD_BENCH_PLAN.md §1.8. A census typed into a document by hand is
`oracle.json`'s original defect in a cheaper costume: nothing can notice when it
stops being true, and "86 devices" reads exactly as authoritative whether it was
measured this morning or guessed two years ago.

So `WORKLOAD.md` is GENERATED by this module and pinned by
`test/test_cloud_census.py`, which re-derives it from the vendored raw data and
compares byte for byte. Editing the document by hand is a test failure; changing
the reading of the dataset without regenerating it is also a test failure.

**Two numbers in CLOUD_BENCH_PLAN.md do not survive this derivation**, and both
are recorded in the document itself rather than silently corrected:

  1. §1.3's "~1,722 table rules" is 1,741. It was computed as 2,941 - 1,219,
     subtracting the internet gateway's 19 rules along with the 1,200 host
     injectors -- while also counting the gateway as one of the 86 tables. The
     gateway's rules ARE table rules. `routes.json` has carried 1,741 entries
     all along, so the model was never wrong; only the figure describing it was.

  2. §1.1's "~1,555" for `packet.ipv4.source` is 1,558. The tilde is the tell:
     that table mixes two different measurements. Per-BIT density genuinely
     varies across an IP field, because a /22 constrains 22 of its 32 bits and a
     /30 constrains 30 -- source runs 1,558 down to 0 and destination 1,682 down
     to 14. This module counts RULES WHOSE FIELD IS NOT FULLY WILDCARDED, one
     well-defined number per field, which is why no row here needs a tilde.

`85` versus `86` is NOT such a disagreement, and the distinction is worth
keeping. §1.2 classifies by "appears as both a rule in-port and an out-port",
which yields 85 and then adds the gateway back by hand. `cloud_tf.classify_nodes`
classifies by "has rules of its own", which yields 86 directly. The gateway is
the whole difference: every one of its 19 rules either DROPS or NATs, so it
never appears as anybody's out-port, and the structural test would file a
drop-only device as a traffic source. Both readings agree on the model; one of
them needs a footnote to get there.
"""

from __future__ import annotations

import collections
import hashlib
import os
import re

from typing import Dict, List, Sequence, Tuple

from bench.wl_cloud.cloud_readme import INTERNET_INDEX, CloudReadme, read_readme
from bench.wl_cloud.cloud_policy import role_endpoints
from bench.wl_cloud.cloud_tf import (
    CLOUD_MAPPING,
    FAVE_MAPPING,
    NodeModel,
    Rule,
    classify_nodes,
    node_name,
    parse_tf,
    read_match_field,
)


HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, 'cloud-tf')
DOCUMENT = os.path.join(HERE, 'WORKLOAD.md')


class CensusError(Exception):
    """ A node or rule this module will not silently file somewhere. """


#: Device classes, keyed by what `cloud_tf.node_name` calls them. Ordered
#: north to south so the rendered tables read as the topology does.
_DEVICE_CLASSES: Sequence[Tuple[str, 're.Pattern']] = (
    ('internet_gw', re.compile(r'internet_gw$')),
    ('core', re.compile(r'dc\d+_core$')),
    ('leaf_in', re.compile(r'dc\d+_leaf\d+_in$')),
    ('leaf_out', re.compile(r'dc\d+_leaf\d+_out$')),
)

#: Non-device node classes: the generators and the probes.
_ENDPOINT_CLASSES: Sequence[Tuple[str, 're.Pattern']] = (
    ('host_tx', re.compile(r'dc\d+_leaf\d+_host\d+_tx$')),
    ('host_rx', re.compile(r'dc\d+_leaf\d+_host\d+_rx$')),
    ('internet_rx', re.compile(r'internet_rx$')),
)

#: What each device class is, in one line, for the rendered table.
_CLASS_PROSE: Dict[str, str] = {
    'internet_gw': 'the one gateway: anti-spoof filter and inbound destination-NAT',
    'core': 'datacenter cores: inter-leaf and inter-datacenter routing, outbound source-NAT',
    'leaf_in': 'leaf-router ingress: the ACL, and the decision to go up or across',
    'leaf_out': 'leaf-router egress: host distribution, nothing else',
    'host_tx': 'host transmit nodes -> FaVe generators',
    'host_rx': 'host receive nodes -> FaVe probes',
    'internet_rx': 'the internet egress sink -> one more probe',
}

#: The four functions a device rule can have. Structural definitions, in the
#: order they are tested -- a rule is classified by what it DOES, never by which
#: device it sits on, so the taxonomy cannot beg the question it is asked.
_RULE_FUNCTIONS = ('deny', 'nat', 'acl-permit', 'forward')

_RULE_FUNCTION_PROSE: Dict[str, str] = {
    'deny': 'no out-port: the packet is discarded',
    'nat': 'a `rw` rule: it rewrites the address it forwards on',
    'acl-permit': 'constrains a transport port, so it admits a SERVICE rather than a destination',
    'forward': 'everything else: a routing decision on the destination alone, or an unconditioned uplink',
}

_TRANSPORT_FIELDS = ('packet.upper.sport', 'packet.upper.dport')


def device_class(name: str) -> str:
    """ Which device class a node name belongs to. Refuses the unclassified.

    A default bucket here would let a node the reading does not understand be
    counted as though it were understood, which is the failure §1.8 is about.
    """
    for label, pattern in _DEVICE_CLASSES:
        if pattern.match(name):
            return label
    raise CensusError("no device class for node %r" % name)


def endpoint_class(name: str) -> str:
    """ Which endpoint class a non-device node belongs to. Refuses likewise. """
    for label, pattern in _ENDPOINT_CLASSES:
        if pattern.match(name):
            return label
    raise CensusError("no endpoint class for node %r" % name)


def rule_function(rule: Rule) -> str:
    """ What a rule does, from its own shape.

    The ACL test is "constrains a transport port". That is what distinguishes
    an access rule from a routing rule in this dataset -- the generator emits
    permissions as `dst in <service prefix>, proto = tcp, dport = 331+i`, and
    emits routing as a destination prefix and nothing else. Testing the device
    instead ("rules at a leaf ingress are ACLs") would assume the answer.
    """
    if rule.is_drop:
        return 'deny'
    if rule.action == 'rw':
        return 'nat'
    if any(read_match_field(rule.match, f) is not None for f in _TRANSPORT_FIELDS):
        return 'acl-permit'
    return 'forward'


def _digest(path: str) -> str:
    with open(path, 'rb') as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def _oracle_inventory(path: str) -> Tuple[int, int]:
    """ (roles, services) the hand-written oracle phase runs with.

    `Internet` is added because FPL declares it BUILT IN -- `reach.txt` names it
    on three of its five rules and the inventory therefore never defines it, so
    counting `describe role` alone is one short of the 8 roles the run actually
    carries (`roles.json`, and `sources.json`'s 8 generators). The matrix phase
    needs no such correction: `cloud_policy.role_endpoints` already seeds the
    role map with `Internet` for exactly this reason.
    """
    text = open(path).read()
    return (
        len(re.findall(r'^describe\s+role\s', text, re.M)) + 1,
        len(re.findall(r'^describe\s+service\s', text, re.M)),
    )


def census(rules: List[Rule], model: NodeModel, readme: CloudReadme) -> Dict:
    """ Every number `WORKLOAD.md` states, derived from the raw data. """
    devices = collections.Counter(device_class(node_name(n)) for n in model.devices)
    endpoints = collections.Counter(
        endpoint_class(node_name(n)) for n in list(model.sources) + list(model.sinks))

    # rules per (device class, function)
    grid: Dict[Tuple[str, str], int] = collections.Counter()
    for node in model.devices:
        label = device_class(node_name(node))
        for rule in model.rules_at(node):
            grid[(label, rule_function(rule))] += 1

    # the ACL permits split by whether they constrain a source: the ones that
    # do are the matrix's private half, the ones that do not are public.
    sourced = collections.Counter()
    for node in model.devices:
        for rule in model.rules_at(node):
            if rule_function(rule) != 'acl-permit':
                continue
            has = read_match_field(rule.match, 'packet.ipv4.source') is not None
            sourced['sourced' if has else 'source-less'] += 1

    # the topology: device-to-device edges only. A host or internet edge is a
    # generator or a probe attachment, not a link, which is why `topology.json`
    # carries fewer links than the rules carry distinct node pairs.
    device_nodes = set(model.devices)
    links: Dict[Tuple[str, str], set] = collections.defaultdict(set)
    for rule in rules:
        for src in rule.in_ports:
            for dst in rule.out_ports:
                if src in device_nodes and dst in device_nodes:
                    links[(device_class(node_name(src)),
                           device_class(node_name(dst)))].add((src, dst))

    fields = {
        field: sum(
            1 for rule in rules if read_match_field(rule.match, field) is not None)
        for field in CLOUD_MAPPING if field != 'length'
    }

    matrix_endpoints = role_endpoints(readme)
    oracle_roles, oracle_services = _oracle_inventory(
        os.path.join(HERE, 'roles_and_services.txt'))

    return {
        'sha256': {name: _digest(os.path.join(RAW, name))
                   for name in ('network.tf', 'README.txt')},
        'rules_total': len(rules),
        'actions': collections.Counter(r.action for r in rules),
        'devices': devices,
        'endpoints': endpoints,
        'nodes_total': len(model.devices) + len(model.sources) + len(model.sinks),
        'grid': grid,
        'acl_sourced': sourced,
        'links': {pair: len(edges) for pair, edges in links.items()},
        'source_rules': sum(len(model.rules_at(n)) for n in model.sources),
        'device_rules': sum(len(model.rules_at(n)) for n in model.devices),
        'drop_nodes': len({p for r in rules if r.is_drop for p in r.in_ports}),
        'fields': fields,
        'protocols': sorted(
            {read_match_field(r.match, 'packet.ipv6.proto') for r in rules} - {None}),
        'ports': sorted(
            {read_match_field(r.match, f) for r in rules for f in _TRANSPORT_FIELDS}
            - {None}),
        'services': len(readme.services),
        'roles': len(readme.roles),
        'internet_index': readme.internet_index,
        'port_base': readme.service_port_base,
        'authorised_pairs': len(readme.authorised_pairs()),
        'matrix_symmetric': all(
            readme.permits(i, j) == readme.permits(j, i)
            for i in readme.roles for j in readme.roles),
        'matrix_diagonal': sum(1 for i in readme.roles if readme.permits(i, i)),
        'matrix_roles': len(matrix_endpoints),
        'matrix_endpoints': sum(len(v) for v in matrix_endpoints.values()),
        'oracle_roles': oracle_roles,
        'oracle_services': oracle_services,
        'mapping': dict(CLOUD_MAPPING),
        'fave_mapping': dict(FAVE_MAPPING),
    }


def _n(value: int) -> str:
    """ A count, in the plan's own thousands-separated spelling. """
    return '{:,}'.format(value)


def _table(header: Sequence[str], rows: Sequence[Sequence[str]],
           align: str = '') -> List[str]:
    align = align or 'l' * len(header)
    sep = {'l': '---', 'r': '---:', 'c': ':---:'}
    out = ['| ' + ' | '.join(header) + ' |',
           '|' + '|'.join(sep[a] for a in align) + '|']
    out.extend('| ' + ' | '.join(str(c) for c in row) + ' |' for row in rows)
    return out


def render(c: Dict) -> str:
    """ `WORKLOAD.md`, from the census. """
    n = c['devices']
    e = c['endpoints']
    grid = c['grid']
    out: List[str] = []
    w = out.append

    w('# wl_cloud: what the workload contains')
    w('')
    w('**This file is GENERATED** by `cloud_census.py` out of the two vendored raw')
    w('files, and `test/test_cloud_census.py` re-derives it and compares byte for')
    w('byte. Do not edit it by hand -- run `python3 -m bench.wl_cloud.cloud_census`')
    w('from `fave/` instead. CLOUD_BENCH_PLAN.md §1.8 is why: a census nobody can')
    w('recompute is indistinguishable from a census that stopped being true.')
    w('')
    w('Everything below is measured from these exact bytes:')
    w('')
    out.extend(_table(('file', 'sha256'),
                      [('`cloud-tf/%s`' % k, '`%s`' % v)
                       for k, v in sorted(c['sha256'].items())]))
    w('')
    w('`network.tf` states no topology, no device list and no field layout. All')
    w('three are derived -- see §1.1 and §1.2 of the plan for the derivations and')
    w('the cross-checks that make them measurements rather than guesses.')
    w('')

    w('## Devices: %s' % _n(sum(n.values())))
    w('')
    w('Ports in this dataset are **nodes, not interfaces**: a rule `fwd A -> B`')
    w('means a packet at node A moves to node B. A node carrying rules of its own')
    w('is a device; one that only injects is a generator; one that only receives is')
    w('a probe.')
    w('')
    out.extend(_table(
        ('class', 'count', 'what it is'),
        [(('`%s`' % k), n[k], _CLASS_PROSE[k]) for k, _ in _DEVICE_CLASSES],
        align='lrl'))
    w('')
    w('> CLOUD_BENCH_PLAN.md §1.2 says **85** here and then adds the gateway back in')
    w('> §1.3. It classifies by "appears as both a rule in-port and an out-port",')
    w('> and every one of the gateway\'s %d rules either drops or NATs, so the'
      % sum(grid[('internet_gw', f)] for f in _RULE_FUNCTIONS))
    w('> gateway never appears as anybody\'s out-port. `cloud_tf.classify_nodes`')
    w('> classifies by "has rules of its own" and gets %d directly, which is what'
      % sum(n.values()))
    w('> the model is built from. The two readings agree; one needs a footnote.')
    w('')
    w('Around the devices, %s endpoint nodes:' % _n(sum(e.values())))
    w('')
    out.extend(_table(
        ('class', 'count', 'what it is'),
        [(('`%s`' % k), _n(e[k]), _CLASS_PROSE[k]) for k, _ in _ENDPOINT_CLASSES],
        align='lrl'))
    w('')
    w('%s nodes are named in total. The host count is 5 datacenters x 8 leaf'
      % _n(c['nodes_total']))
    w('routers x 30 hosts, which is `README.txt`\'s generator parameters exactly --')
    w('and the `.tf` file states none of them.')
    w('')

    w('## Topology: %s links' % _n(sum(c['links'].values())))
    w('')
    out.extend(_table(
        ('from', 'to', 'links'),
        [('`%s`' % a, '`%s`' % b, v)
         for (a, b), v in sorted(c['links'].items(), key=lambda kv: -kv[1])],
        align='llr'))
    w('')
    w('A fat tree of height 1 per datacenter, five datacenters in a full mesh')
    w('above them, and one gateway above that. The %s host attachments and the'
      % _n(e['host_tx'] + e['host_rx']))
    w('core-to-`internet_rx` egresses are generators and probes rather than links,')
    w('which is why `topology.json` carries %s and not more.'
      % _n(sum(c['links'].values())))
    w('')

    w('## Rules: %s' % _n(c['rules_total']))
    w('')
    w('%s `fwd` and %d `rw`. %d of them have no out-port and discard, spread over'
      % (_n(c['actions']['fwd']), c['actions']['rw'],
         grid[('leaf_in', 'deny')] + grid[('internet_gw', 'deny')]))
    w('%d distinct nodes.' % c['drop_nodes'])
    w('')
    w('%s sit on the host transmit nodes -- one each, a pure source-address'
      % _n(c['source_rules']))
    w('constraint -- and become FaVe **generators**, not table rules. The other')
    w('**%s are the data plane**, and that is the number `routes.json` carries.'
      % _n(c['device_rules']))
    w('')
    w('> CLOUD_BENCH_PLAN.md §1.3 says "~1,722 table rules". It is %s. The figure'
      % _n(c['device_rules']))
    w('> was computed as %s - %s, subtracting the gateway\'s %d rules along with'
      % (_n(c['rules_total']),
         _n(c['source_rules'] + sum(grid[('internet_gw', f)]
                                    for f in _RULE_FUNCTIONS)),
         sum(grid[('internet_gw', f)] for f in _RULE_FUNCTIONS)))
    w('> the %s host injectors, while also counting the gateway as one of the %d'
      % (_n(c['source_rules']), sum(n.values())))
    w('> tables. The gateway\'s rules ARE table rules. The model was never wrong --')
    w('> only the figure describing it.')
    w('')
    w('### By function')
    w('')
    w('A rule is classified by **what it does**, never by which device it sits on:')
    w('')
    out.extend(_table(('function', 'test'),
                      [('`%s`' % f, _RULE_FUNCTION_PROSE[f]) for f in _RULE_FUNCTIONS]))
    w('')
    out.extend(_table(
        ('device class',) + tuple('`%s`' % f for f in _RULE_FUNCTIONS) + ('total',),
        [tuple(['`%s`' % k]
               + [_n(grid[(k, f)]) if grid[(k, f)] else '' for f in _RULE_FUNCTIONS]
               + [_n(sum(grid[(k, f)] for f in _RULE_FUNCTIONS))])
         for k, _ in _DEVICE_CLASSES]
        + [tuple(['**total**']
                 + ['**%s**' % _n(sum(grid[(k, f)] for k, _ in _DEVICE_CLASSES))
                    for f in _RULE_FUNCTIONS]
                 + ['**%s**' % _n(c['device_rules'])])],
        align='l' + 'r' * (len(_RULE_FUNCTIONS) + 1)))
    w('')
    w('So the workload is **%s ACL rules** -- %s permits and %s denials, the'
      % (_n(sum(grid[(k, f)] for k, _ in _DEVICE_CLASSES
                for f in ('acl-permit', 'deny'))),
         _n(sum(grid[(k, 'acl-permit')] for k, _ in _DEVICE_CLASSES)),
         _n(sum(grid[(k, 'deny')] for k, _ in _DEVICE_CLASSES))))
    w('latter being %d leaf default-denies plus the gateway\'s %d anti-spoof drops'
      % (grid[('leaf_in', 'deny')], grid[('internet_gw', 'deny')]))
    w('-- against **%s forwarding rules** and **%d NAT rules**.'
      % (_n(sum(grid[(k, 'forward')] for k, _ in _DEVICE_CLASSES)),
         sum(grid[(k, 'nat')] for k, _ in _DEVICE_CLASSES)))
    w('')
    w('The shape of each class is regular enough to state outright:')
    w('')
    w('* **`leaf_in`** carries the whole access-control layer: %s permits, one'
      % _n(grid[('leaf_in', 'acl-permit')]))
    w('  unconditioned default-deny per leaf (`dst in <my /25>` -> DROP), and one')
    w('  unconditioned uplink per leaf to its core.')
    w('* **`leaf_out`** is pure distribution: %s `/30` host routes, %d per leaf.'
      % (_n(grid[('leaf_out', 'forward')]),
         grid[('leaf_out', 'forward')] // n['leaf_out']))
    w('* **`core`** carries %d routes each -- 8 local leaf `/25`s and 4 peer-'
      % (grid[('core', 'forward')] // n['core']))
    w('  datacenter `/22`s -- plus the outbound source-NAT.')
    w('* **`internet_gw`** is %d anti-spoof drops (`121.140.254.0/27`, `127/8`,'
      % grid[('internet_gw', 'deny')])
    w('  `10/8`, `172.16/12`, `192.168/16`) and %d destination-NAT rules.'
      % grid[('internet_gw', 'nat')])
    w('')
    w('### The ACL permits split by source')
    w('')
    out.extend(_table(
        ('permits', 'count', 'meaning'),
        [('constrain a source', c['acl_sourced']['sourced'],
          "the matrix's private half: one rule per authorised pair, per direction"),
         ('constrain no source', c['acl_sourced']['source-less'],
          'a PUBLIC service -- admits every source, not only the Internet')],
        align='lrl'))
    w('')
    w('That second row is the workload\'s own finding, not an artefact of the')
    w('reading: the generator implements "the Internet may reach service *i*" as a')
    w('rule with no source match at all, so every public service is reachable from')
    w('every role while the matrix authorises far fewer. `matrix/reach.txt` is')
    w('expected to report violations concentrated entirely there, and')
    w('`matrix/reach_public.txt` is expected to be clean.')
    w('')

    w('## Header fields')
    w('')
    w('The 128-bit match layout was **recovered by measuring** which bit positions')
    w('the %s rules constrain; nothing in the file declares it. It is not'
      % _n(c['rules_total']))
    w('`wl_stanford`\'s layout, but both put the destination at bit 48 -- so a')
    w('reader using the wrong one still produces plausible forwarding and goes')
    w('wrong only on the ACL and NAT fields.')
    w('')
    order = list(c['mapping'])
    out.extend(_table(
        ('field', 'offset', 'width', 'rules constraining it'),
        [('`%s`' % field, c['mapping'][field],
          c['mapping'][order[i + 1]] - c['mapping'][field],
          _n(c['fields'][field]) if c['fields'][field] else '**0 -- never used**')
         for i, field in enumerate(order) if field != 'length'],
        align='lrrr'))
    w('')
    w('Counted as **rules whose field is not fully wildcarded** -- one well-defined')
    w('number per field. CLOUD_BENCH_PLAN.md §1.1 tabulates per-BIT density')
    w('instead, which for an IP field is a range rather than a number (a `/22`')
    w('constrains 22 of its 32 bits and a `/30` constrains 30), and its "~1,555"')
    w('for the source is %s under this definition.'
      % _n(c['fields']['packet.ipv4.source']))
    w('')
    w('Five of the seven are exercised. The only protocol value that ever appears')
    w('is %s (TCP) and the only transport ports are %d..%d, as destination and as'
      % (', '.join(str(p) for p in c['protocols']), c['ports'][0], c['ports'][-1]))
    w('source both.')
    w('')
    w('FaVe runs with one field the dataset does not have: **`related` at bit %d**,'
      % c['fave_mapping']['related'])
    w('taking the header to %d bits. `bench/reach_csv_to_checks.py` puts'
      % c['fave_mapping']['length'])
    w('`f=related:0` on every conditionally permitted check, and this network has no')
    w('connection tracking at all -- no rule and no generator ever constrains the')
    w('field, so it stays wildcard and the condition overlaps every flow. That is')
    w('exactly the "all packets are new" reading a stateless model deserves, and it')
    w('is why the policy uses `--->` rather than `<->>`.')
    w('')

    w('## The ACL matrix, and the two phases over it')
    w('')
    w('`README.txt` carries a **%dx%d matrix over %d roles**: services 0-%d plus'
      % (c['roles'], c['roles'], c['roles'], c['services'] - 1))
    w('the Internet at index %d. It is %s, its diagonal carries %d permission%s,'
      % (c['internet_index'],
         'fully symmetric' if c['matrix_symmetric'] else 'NOT symmetric',
         c['matrix_diagonal'], '' if c['matrix_diagonal'] == 1 else 's'))
    w('and it authorises **%s ordered pairs** of %s -- %.1f%% density.'
      % (_n(c['authorised_pairs']), _n(c['roles'] ** 2),
         100.0 * c['authorised_pairs'] / c['roles'] ** 2))
    w('')
    w('The service algebra is measured, not assumed:')
    w('')
    w('    service i  <->  TCP port %d + i  <->  public address 121.140.254.i'
      % c['port_base'])
    w('')
    w('and index %d being the Internet is confirmed by four independently derived'
      % c['internet_index'])
    w('sets coinciding exactly (`test_cloud_readme.py`). Two phases run over this')
    w('same data plane:')
    w('')
    out.extend(_table(
        ('phase', 'roles', 'endpoints', 'services', 'provenance of the policy'),
        [('oracle', c['oracle_roles'], c['oracle_roles'], c['oracle_services'],
          'HAND-WRITTEN: the dataset ships no inventory, so §1.9 states its six '
          '`.smt2` questions as FPL'),
         ('matrix', c['matrix_roles'], c['matrix_endpoints'], c['services'],
          "GENERATED from `README.txt`: the roles, the services and the policy "
          "are all the dataset's")],
        align='lrrrl'))
    w('')
    w('Which is why the two phases\' `roles_and_services.txt` and `reach.txt` have')
    w('the same names and do not share a directory. See `README.md`.')
    w('')
    return '\n'.join(out) + '\n'


def build() -> str:
    """ Read the raw data and render the document. """
    with open(os.path.join(RAW, 'network.tf')) as handle:
        rules = parse_tf(handle)
    readme = read_readme(os.path.join(RAW, 'README.txt'))
    return render(census(rules, classify_nodes(rules), readme))


def main() -> None:
    document = build()
    with open(DOCUMENT, 'w') as handle:
        handle.write(document)
    print("wrote %s (%d bytes)" % (DOCUMENT, len(document)))


if __name__ == '__main__':
    main()
